### ISSUE TITLE
.env / TRPC example (VITE_API_URL)

### ISSUE THREAD

**Issue by Awolize** [noahflk/react-trpc-turbo#1]
Hello, 

First off, thank you for this boilerplate repo! I just wanted to add that you need to create a .env file that includes the VITE_API_URL path variable in order for the TRPC calls to work. An example of a TRPC call would also be very helpful. At least mentioning it in the readme could be enough.

.env
```.env
VITE_API_URL = "http://localhost:3000"
```

index.lazy.tsx
```.ts
const userQuery = trpc.hello.get.useQuery({ name: 'Firstname' });
```

**Comment by noahflk** [comment]
Much needed feedback. Thank you @Awolize 

Fixed in #f8359c9
